@echo off
setlocal EnableDelayedExpansion

REM ============================================================
REM me.bat - Batch Symbolic Link Creator
REM ============================================================

REM --------- Arguments Parsing (Modified) ----------
REM 格式: me.bat "源目录" "目标目录" [模式] [忽略列表]

REM %~1 去除引号，确保路径格式正确
set "SRC=%~1"
set "DEST=%~2"
set "MODE=%~3"
set "IGNORE=%~4"

REM -- 校验必填参数 --
if "%SRC%"=="" (
    echo [ERROR] Missing Source Directory.
    echo Usage: %~nx0 "SRC_PATH" "DEST_PATH" [MODE] [IGNORE_LIST]
    pause
    exit /b 1
)

if "%DEST%"=="" (
    echo [ERROR] Missing Destination Directory.
    pause
    exit /b 1
)

REM -- 设置默认值 --
if "%MODE%"=="" set "MODE=MANUAL"

if "%IGNORE%"=="" set "IGNORE=.test-test-no-exist;.test-2-no-exist"


REM --------- Initialization ----------
echo prepare env
if not exist "%~dp0output\" (
    md "%~dp0output"
)

set "MANUAL_CMDS="
set "MANUAL_FILE=%~dp0output\manual.cmd"
set "RUN_LOG=%~dp0output\run.log"


REM ======= Generate Standard Timestamp (Using PowerShell instead of WMIC) =======
REM Get date in yyyyMMdd_HHmmss format
for /f "usebackq delims=" %%I in (`powershell -NoProfile -Command "Get-Date -Format 'yyyyMMdd_HHmmss'"`) do set "TS=%%I"

echo ======= Initialize Log File =======
(
echo ====== me.bat Run Log ======
echo Run Time: %date% %time%
echo SRC=%SRC%
echo DEST=%DEST%
echo MODE=%MODE%
echo IGNORE=%IGNORE%
echo ---------------------------------------
) > "!RUN_LOG!"

echo ======= Initialize Manual Script =======
(
echo @echo off
echo REM === Automatically generated by me.bat, please run as Administrator ===
echo REM Generated at: %date% %time%
echo.
) > "!MANUAL_FILE!"

echo.
echo === Processing Started ===
echo Source:      %SRC%
echo Destination: %DEST%
echo Mode:        %MODE%
echo Ignore List: %IGNORE%
echo.


PAUSE


REM ============================================================
REM ========== 1. Process [Directories] ==========
REM ============================================================
echo [Scanning Subdirectories...]
for /D %%F in ("%SRC%\*") do (
    call :ProcessItem "%%F" "DIR"
)

REM ============================================================
REM ========== 2. Process [Files] ==========
REM ============================================================
echo.
echo [Scanning Files...]
for %%F in ("%SRC%\*") do (
    REM Exclude directories
    if not exist "%%F\" (
        call :ProcessItem "%%F" "FILE"
    )
)

REM Jump to the end correctly
goto :EndScript

REM ============================================================
REM ========== Core Processing Subroutine ==========
REM ============================================================
:ProcessItem
set "pPath=%~1"
set "pType=%~2"
set "name=%~nx1"
set "target=%DEST%\%~nx1"

REM ---- Ignore Check ----
echo !IGNORE! | findstr /i /c:"!name!" >nul
if !errorlevel!==0 (
    echo [IGNORE] Skipping: !target!
    goto :eof
)

if exist "!target!" (
    REM ---- Check if it is a Symbolic Link / Junction ----
    for %%T in ("!target!") do set "attr=%%~aT"
    
    echo !attr! | findstr /i "l" >nul
    if !errorlevel!==0 (
        echo [RELINK] Recreating old link: !target!
        if /I "%pType%"=="DIR" (
            echo rmdir "!target!" >> "!RUN_LOG!"
            echo mklink /d "!target!" "!pPath!" >> "!RUN_LOG!"
            rmdir "!target!"
            mklink /d "!target!" "!pPath!"
        ) else (
            echo del "!target!" >> "!RUN_LOG!"
            echo mklink "!target!" "!pPath!" >> "!RUN_LOG!"
            del "!target!"
            mklink "!target!" "!pPath!"
        )
        goto :eof
    )

    REM ======= Real Content Exists =======
    set "ZIP_PATH=%~dp0backup_%TS%_!name!.zip"
    echo [BACKUP] Backing up real content -> !ZIP_PATH!
    
    powershell -NoProfile -Command "Compress-Archive -Path '!target!' -DestinationPath '!ZIP_PATH!' -Force" 2>nul

    if /I "%MODE%"=="AUTO" (
        echo [AUTO] Deleting and recreating: !target!
        if /I "%pType%"=="DIR" (
            echo rmdir /s /q "!target!" >> "!RUN_LOG!"
            echo mklink /d "!target!" "!pPath!" >> "!RUN_LOG!"
            rmdir /s /q "!target!"
            mklink /d "!target!" "!pPath!"
        ) else (
            echo del /f /q "!target!" >> "!RUN_LOG!"
            echo mklink "!target!" "!pPath!" >> "!RUN_LOG!"
            del /f /q "!target!"
            mklink "!target!" "!pPath!"
        )
    ) else (
        echo [BLOCK] Real content detected, writing to manual script: !target!
        if /I "%pType%"=="DIR" (
            echo rmdir /s /q "!target!" >> "!MANUAL_FILE!"
            echo mklink /d "!target!" "!pPath!" >> "!MANUAL_FILE!"
        ) else (
            echo del "!target!" >> "!MANUAL_FILE!"
            echo mklink "!target!" "!pPath!" >> "!MANUAL_FILE!"
        )
        echo. >> "!MANUAL_FILE!"
        set "MANUAL_CMDS=1"
    )
    goto :eof
)

REM ---- Create New Link ----
echo [CREATE] !target!
if /I "%pType%"=="DIR" (
    echo mklink /d "!target!" "!pPath!" >> "!RUN_LOG!"
    mklink /d "!target!" "!pPath!"
) else (
    echo mklink "!target!" "!pPath!" >> "!RUN_LOG!"
    mklink "!target!" "!pPath!"
)
goto :eof

:EndScript
echo.
echo === Processing Complete ===
echo.

if defined MANUAL_CMDS (
  echo ------------------------------------------------------------
  echo Manual script generated:
  echo   !MANUAL_FILE!
  echo ------------------------------------------------------------
) else (
  echo No manual actions required.
)

echo Runned code save to log:
echo    "!RUN_LOG!"

pause